### ISSUE TITLE
Logout button needed

### ISSUE THREAD

**Issue by smitjiwani** [smitjiwani/linkedIn_clone#2]
Problem
Once, logged in, when you click the avatar, it logs out.

Solution
When you click on the avatar a dropdown menu should appear and should have a logout option like so.

![Screenshot 2023-06-23 162941](https://github.com/smitjiwani/linkedIn_clone/assets/78549024/29dcf62f-5801-4166-84b3-e8f48087cadb)
![Screenshot 2023-06-23 163040](https://github.com/smitjiwani/linkedIn_clone/assets/78549024/7f88e9f3-af54-4ed9-8ccb-d33c565a0377)

**Comment by KarthikShetty5** [comment]
Can u assign me this , i can do this

**Comment by KarthikShetty5** [comment]
hey, can you
